name: Manual stage
on:
  workflow_dispatch:
jobs:
  manual-stage:
    runs-on: ubuntu-latest
    steps:
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
        az containerapp ingress traffic set --name bgdfinal --resource-group ACRforNODEJSapp-RG --label-weight green=100
        az containerapp revision label swap -n bgdfinal -g ACRforNODEJSapp-RG --source green --target blue
